/**
 * Responsive image pipeline.
 *
 * For every source JPEG under public/images, renders AVIF + WebP + JPEG
 * derivatives at a set of responsive widths (never upscaling past the source),
 * then writes src/lib/images.generated.js mapping each `/images/...` source path
 * to its `srcSet` / `webp` / `avif` strings. `images.js` layers those on at load.
 *
 * Run with: `npm run images`  (needs the `sharp` dev dependency, already installed).
 *
 * Idempotent: skips a derivative that is already newer than its source, so
 * re-runs are cheap. Delete public/images/**\/*-<w>.{avif,webp,jpg} to force a rebuild.
 */
import sharp from "sharp"
import { readdir, stat, writeFile, mkdir } from "node:fs/promises"
import { existsSync } from "node:fs"
import { dirname, extname, join, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, "..")
const IMAGES_DIR = join(ROOT, "public", "images")
const MANIFEST = join(ROOT, "src", "lib", "images.generated.js")

/** Candidate widths; each source only emits those <= its own width, plus itself. */
const WIDTHS = [400, 640, 828, 1080, 1366, 1600, 1920]
const QUALITY = { avif: 50, webp: 74, jpeg: 78 }

async function walk(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else if (/\.jpe?g$/i.test(entry.name) && !/-\d+\.jpe?g$/i.test(entry.name)) out.push(full)
  }
  return out
}

/** True when `out` exists and is newer than `src` (so we can skip regenerating). */
async function isFresh(out, src) {
  if (!existsSync(out)) return false
  const [o, s] = await Promise.all([stat(out), stat(src)])
  return o.mtimeMs >= s.mtimeMs
}

function publicPath(absFile) {
  return "/" + relative(join(ROOT, "public"), absFile).split(/[\\/]/).join("/")
}

async function processImage(file) {
  const meta = await sharp(file).metadata()
  const maxW = meta.width || Math.max(...WIDTHS)
  const widths = [...new Set([...WIDTHS.filter((w) => w < maxW), maxW])].sort((a, b) => a - b)
  const base = file.slice(0, file.length - extname(file).length)

  const rows = { avif: [], webp: [], jpeg: [] }
  for (const w of widths) {
    for (const fmt of ["avif", "webp", "jpeg"]) {
      const ext = fmt === "jpeg" ? "jpg" : fmt
      const out = `${base}-${w}.${ext}`
      if (!(await isFresh(out, file))) {
        const pipe = sharp(file).resize({ width: w, withoutEnlargement: true })
        if (fmt === "avif") await pipe.avif({ quality: QUALITY.avif }).toFile(out)
        else if (fmt === "webp") await pipe.webp({ quality: QUALITY.webp }).toFile(out)
        else await pipe.jpeg({ quality: QUALITY.jpeg, mozjpeg: true }).toFile(out)
      }
      rows[fmt].push(`${publicPath(out)} ${w}w`)
    }
  }

  return {
    src: publicPath(file),
    srcSet: rows.jpeg.join(", "),
    webp: rows.webp.join(", "),
    avif: rows.avif.join(", "),
  }
}

async function run() {
  if (!existsSync(IMAGES_DIR)) {
    console.error(`No image directory at ${IMAGES_DIR}`)
    process.exit(1)
  }
  const files = (await walk(IMAGES_DIR)).sort()
  if (!files.length) {
    console.error("No source JPEGs found under public/images.")
    process.exit(1)
  }

  const manifest = {}
  for (const file of files) {
    const entry = await processImage(file)
    manifest[entry.src] = { srcSet: entry.srcSet, webp: entry.webp, avif: entry.avif }
    console.log(`  ✓ ${entry.src}`)
  }

  const body =
    "/**\n" +
    " * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n" +
    " * Run `npm run images` to regenerate.\n" +
    " *\n" +
    " * @type {Record<string, { srcSet?: string, webp?: string, avif?: string }>}\n" +
    " */\n" +
    `export const generatedImageSources = ${JSON.stringify(manifest, null, 2)}\n`

  await mkdir(dirname(MANIFEST), { recursive: true })
  await writeFile(MANIFEST, body, "utf8")
  console.log(`\nWrote ${files.length} image manifests → ${relative(ROOT, MANIFEST)}`)
}

run().catch((err) => {
  console.error("Image optimization failed:", err)
  process.exit(1)
})
